//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chevalresk_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Armure
    {
        public int idItems { get; set; }
        public int Poids { get; set; }
        public string matiere { get; set; }
        public string taille { get; set; }
        public int Id { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
