//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chevalresk_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventaire
    {
        public int Id { get; set; }
        public int ItemId { get; set; }
        public int UserId { get; set; }
        public int QuantiteInventaire { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual User User { get; set; }
    }
}
